version: "3.9"
services:
  dserver-api:
    build: 
      context: ./app
      args:
        - SHA256_KEY=hogehoge
    working_dir: /go/src
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis:6379"
      - "PORT=8080"
      - "CORS_URL=http://localhost"
      - "SQL_URL=postgres://db:5432/dmeeting?user=dmeeting&password=dmeeting_password&sslmode=disable"
      # - "CORS_DOMAINS=[\"http://localhost:3000\",\"http://localhost\",\"http://127.0.0.1\"]"
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=dmeeting
      - POSTGRES_PASSWORD=dmeeting_password
      - POSTGRES_DB=dmeeting
      - TZ=Asia/Tokyo

volumes:
  db:  